# Generated by Django 4.2.3 on 2023-11-22 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0002_userstatistics_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatistics',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proxy.usersite'),
        ),
    ]
